# Generated by Django 3.2.2 on 2021-05-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='RealCountOfStudents',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
