# Generated by Django 3.2.2 on 2021-05-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_lesson_realcountofstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CourseNumber',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
