# Generated by Django 3.2.2 on 2021-05-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_course_coursenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
