# Generated by Django 3.2.2 on 2021-06-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_schedulelesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleLesson',
        ),
    ]
