# Generated by Django 3.2.2 on 2021-06-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_delete_schedulelesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateStart', models.DateField()),
                ('DateFinish', models.DateField()),
                ('DayOfWeek', models.CharField(max_length=20)),
                ('Week', models.PositiveSmallIntegerField()),
                ('LessonName', models.TextField()),
                ('Groups', models.ManyToManyField(to='polls.Group')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.teacher')),
                ('TimeIntervals', models.ManyToManyField(to='polls.TimeInterval')),
                ('TypeOfLesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.typeoflesson')),
            ],
        ),
    ]
